jobs:
# - template: ./job.yml
#   parameters:
#     jobName: macOS
#     vmImage: macOS-latest
#     os: osx
#     setupEnvironmentSteps:
#     - task: Bash@3
#       displayName: Setup environment
#       inputs:
#         targetType: 'inline'
#         script: |
#           set -x
#           # Install stack
#           curl -L https://www.stackage.org/stack/osx-x86_64 | tar xz --strip-components=1 --include '*/stack' -C .
#           # Script for restoring source files modification time from commit to avoid recompilation.
#           curl -sSkL https://gist.githubusercontent.com/lehins/fd36a8cc8bf853173437b17f6b6426ad/raw/4702d0252731ad8b21317375e917124c590819ce/git-modtime.hs -o git-modtime.hs
#           # Restore mod time and setup ghc, if it wasn't restored from cache
#           ./stack script --resolver ${RESOLVER} git-modtime.hs --package base --package time --package directory --package process

# For faster CI turnaround, linux builds are still on Travis
# - template: ./linux.yml
#   parameters:
#     jobName: Linux
#     vmImage: ubuntu-latest
#     os: linux

- template: ./job.yml
  parameters:
    jobName: Windows
    vmImage: windows-latest
    os: windows
    stackRoot: "$(System.DefaultWorkingDirectory)\\s"
    stackWork: ".w"
    stackProjectPath: "$(Build.SourcesDirectory)"
    setupEnvironmentSteps:
    - powershell: |
        xcopy "$env:STACK_ROOT\\bin" "$env:LOCALAPPDATA\\Programs\\stack" /f /s /r /k /i /h /y /b
      displayName: Restore binaries
      condition: eq(variables.STACK_ROOT_RESTORED, 'true')
      continueOnError: true
    - task: Bash@3
      displayName: Setup environment
      inputs:
        targetType: 'inline'
        script: |
          set -x
          # Install stack
          curl -sSkL https://www.stackage.org/stack/windows-x86_64 -o stack.zip
          7z x stack.zip stack.exe -aoa
          # Script for restoring source files modification time from commit to avoid recompilation.
          curl -sSkL https://gist.githubusercontent.com/lehins/fd36a8cc8bf853173437b17f6b6426ad/raw/4702d0252731ad8b21317375e917124c590819ce/git-modtime.hs -o git-modtime.hs
          # Restore mod time and setup ghc, if it wasn't restored from cache
          ./stack script --resolver ${RESOLVER} git-modtime.hs --package base --package time --package directory --package process
    - powershell: |
        xcopy "$env:LOCALAPPDATA\\Programs\\stack" "$env:STACK_ROOT\\bin" /f /s /r /k /i /h /y /b
      displayName: Save binaries
      continueOnError: true
